version: '3.7'
services:
  app:
    container_name: fastify-app
    restart: always
    build: .
    image: 'fastify-app:1.0.0'
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - postgres
      - postgres
    env_file:
      - .env
  postgres:
    image: 'postgres:10.4'
    container_name: fastify-app-postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DATABASE: fastify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
